LOGINPUA/LOGINPUA/Models/Reportes_Despacho.cs
using AD.EntidadesAD;
using CrystalDecisions.CrystalReports.Engine;
using ENTIDADES;
using LN.EntidadesLN;
using LN.Reportes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Diagnostics;

namespace LOGINPUA.Models
{
    public class Reportes_Despacho
    {
        private Object bdConn;

        private readonly BusesAD _loginRepositorio;

        public Reportes_Despacho()
        {
            BusesAD loginRepositorio = new BusesAD(ref bdConn);
            _loginRepositorio = loginRepositorio;
        }
        public string Insertar_rp_comparativo(CC_REPORTE_PICO_PLACA model, string ruta_base)
        {


            ReportDocument rd = new ReportDocument();
            Reporte_Comparativo dsReporte = new Reporte_Comparativo();

            //IMPORTAR TABLEADAPTER.
            rd.Dispose();
            var dtFormato = new Reporte_Comparativo.TBREGISTROPICOPLACADataTable();
            //RECORRER LISTAS.

            string fecha_in = model.FECHA_INICIO.ToString();

            var dr = dtFormato.NewRow();

            string corredor = model.CORREDOR;





            double vel_ida_t = 0.0;
            double vel_vuelta_t = 0.0;
            double vel_vuelta_m = 0.0;
            double vel_ida_m = 0.0;



            DateTime tiempo1 = Convert.ToDateTime(model.TIEMPO_PROM_A_1);
            DateTime tiempo2 = Convert.ToDateTime(model.TIEMPO_PROM_A_2);
            double minutos_ida_m = tiempo2.Subtract(tiempo1).TotalMinutes;

            DateTime tiempo3 = Convert.ToDateTime(model.TIEMPO_PROM_B_1);
            DateTime tiempo4 = Convert.ToDateTime(model.TIEMPO_PROM_B_2);
            double minutos_vuelta_m = tiempo4.Subtract(tiempo3).TotalMinutes;


            DateTime tiempo5 = Convert.ToDateTime(model.TIEMPO_PROM_A_3);
            DateTime tiempo6 = Convert.ToDateTime(model.TIEMPO_PROM_A_4);
            double minutos_ida_t = tiempo6.Subtract(tiempo5).TotalMinutes;

            DateTime tiempo7 = Convert.ToDateTime(model.TIEMPO_PROM_B_3);
            DateTime tiempo8 = Convert.ToDateTime(model.TIEMPO_PROM_B_4);
            double minutos_vuelta_t = tiempo8.Subtract(tiempo7).TotalMinutes;



            double vel_1 = Convert.ToDouble(model.VEL_PROMEDIO_A_MAÑANA_IDA);
            double vel_2 = Convert.ToDouble(model.VEL_PROMEDIO_B_MAÑANA_IDA);

            vel_ida_m = vel_1 == 0 ? 0 : ((vel_2 - vel_1) / vel_1) * 100;
            vel_ida_m = Math.Round(vel_ida_m, 1);

            double vel_3 = Convert.ToDouble(model.VEL_PROMEDIO_A_MAÑANA_VUELTA);
            double vel_4 = Convert.ToDouble(model.VEL_PROMEDIO_B_MAÑANA_VUELTA);

            vel_vuelta_m = vel_3 == 0 ? 0 : ((vel_4 - vel_3) / vel_3) * 100;
            vel_vuelta_m = Math.Round(vel_vuelta_m, 1);

            double vel_5 = Convert.ToDouble(model.VEL_PROMEDIO_A_TARDE_IDA);
            double vel_6 = Convert.ToDouble(model.VEL_PROMEDIO_B_TARDE_IDA);
            vel_ida_t = vel_5 == 0 ? 0 : ((vel_6 - vel_5) / vel_5) * 100;
            vel_ida_t = Math.Round(vel_ida_t, 1);
            double vel_7 = Convert.ToDouble(model.VEL_PROMEDIO_A_TARDE_VUELTA);
            double vel_8 = Convert.ToDouble(model.VEL_PROMEDIO_B_TARDE_VUELTA);
            vel_vuelta_t = vel_7 == 0 ? 0 : ((vel_8 - vel_7) / vel_7) * 100;
            vel_vuelta_t = Math.Round(vel_vuelta_t, 1);
            dr["TIEMPO_IDA"] = model.M_IDA + "-" + model.M_VUELTA;
            dr["TIEMPO_VUELTA"] = model.T_IDA + "-" + model.T_VUELTA;
            dr["MINUTOS_IDA_M"] = minutos_ida_m;
            dr["MINUTOS_VUELTA_M"] = minutos_vuelta_m;
            dr["MINUTOS_IDA_T"] = minutos_ida_t;
            dr["MINUTOS_VUELTA_T"] = minutos_vuelta_t;
            dr["CORREDOR"] = corredor;
            dr["VELOCIDAD_IDA_M"] = vel_ida_m;
            dr["VELOCIDAD_VUELTA_M"] = vel_vuelta_m;
            dr["VELOCIDAD_IDA_T"] = vel_ida_t;
            dr["VELOCIDAD_VUELTA_T"] = vel_vuelta_t;
            dr["VEL_PROMEDIO_A_MAÑANA_IDA"] = model.VEL_PROMEDIO_A_MAÑANA_IDA;
            dr["VEL_PROMEDIO_A_MAÑANA_VUELTA"] = model.VEL_PROMEDIO_A_MAÑANA_VUELTA;
            dr["TIEMPO_PROM_A_1"] = model.TIEMPO_PROM_A_1;
            dr["TIEMPO_PROM_B_1"] = model.TIEMPO_PROM_B_1;
            dr["VEL_PROMEDIO_B_MAÑANA_IDA"] = model.VEL_PROMEDIO_B_MAÑANA_IDA;
            dr["VEL_PROMEDIO_B_MAÑANA_VUELTA"] = model.VEL_PROMEDIO_B_MAÑANA_VUELTA;
            dr["TIEMPO_PROM_A_2"] = model.TIEMPO_PROM_A_2;
            dr["TIEMPO_PROM_B_2"] = model.TIEMPO_PROM_B_2;
            dr["VEL_PROMEDIO_A_TARDE_IDA"] = model.VEL_PROMEDIO_A_TARDE_IDA;
            dr["VEL_PROMEDIO_A_TARDE_VUELTA"] = model.VEL_PROMEDIO_A_TARDE_VUELTA;
            dr["TIEMPO_PROM_A_3"] = model.TIEMPO_PROM_A_3;
            dr["TIEMPO_PROM_B_3"] = model.TIEMPO_PROM_B_3;

            dr["VEL_PROMEDIO_B_TARDE_IDA"] = model.VEL_PROMEDIO_B_TARDE_IDA;
            dr["VEL_PROMEDIO_B_TARDE_VUELTA"] = model.VEL_PROMEDIO_B_TARDE_VUELTA;
            dr["TIEMPO_PROM_A_4"] = model.TIEMPO_PROM_A_4;
            dr["TIEMPO_PROM_B_4"] = model.TIEMPO_PROM_B_4;
            dr["FECHA_1"] = model.FECHA_INICIO;
            dr["FECHA_2"] = model.FECHA_FIN;
            dtFormato.Rows.Add(dr);

            //CARGAR TABLAS.
            dsReporte.Tables["TBREGISTROPICOPLACA"].Merge(dtFormato);
            /* GUARDAR LOS DATOS EN EL DATASET*/
            rd = new REPORTE_COMPARATIVO();
            rd.SetDataSource(dsReporte);
            /*CREAR PDF*/
            String resultado = "FORMATO_REPORTE_DESPACHO.pdf";
            System.IO.File.Delete(ruta_base + @"Download\" + resultado);
            rd.ExportToDisk(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat, ruta_base + @"Download\" + resultado);
            rd.Close();
            return resultado;
        }
    }
}

LOGINPUA/LOGINPUA/Controllers/SupervisorController.cs
using ENTIDADES;
using LN.EntidadesLN;
using LOGINPUA.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpreadsheetLight;
using Newtonsoft.Json;


namespace LOGINPUA.Controllers
{
    public class SupervisorController : Controller
    {
        private readonly PerfilLN _PerfilLN;
        Util.Util utilidades = new Util.Util();

        private readonly LoginLN _LoginLN;

        private readonly AccesoLN _AccesoLN;
        private readonly AccEmpLN _AccEmpLN;
         private readonly BUSESLN _BusesLN;
   
        CC_CONDUCTORES model = new CC_CONDUCTORES();
        BusesModel buse_model = new BusesModel();

        public SupervisorController(ConductoresLN ConductoresLN, LoginLN LoginLN, AccesoLN AccesoLN, AccEmpLN AccEmpLN, DistanciaLN DistanciaLN, BUSESLN BusesLN, CorredoresLN CorredorLN, RutaLN RutaLN, RegistroPicoPlacaLN registroVelocidadPPlaca)
        {
            _LoginLN = LoginLN;
            _AccesoLN = AccesoLN;
            _AccEmpLN = AccEmpLN;
             _BusesLN = BusesLN;
   
        }
        public ActionResult Index()
        {
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                return View();
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
        }



        public ActionResult Fuera_Campo()
        {
            List<CC_CONDUCTORES> lista = _BusesLN.Listar_Placa();
            ViewBag.lista = new SelectList(lista, "PLACA", "PLACA");

            DateTime fecha_Actual = DateTime.Now;
            string fecha_nombre = fecha_Actual.ToString("dd/MM/yyyy");
            string hora_actual = fecha_Actual.ToString("HH:mm:ss");

            ViewBag.fecha_actual = fecha_nombre;
            ViewBag.Hora_actual = hora_actual;

            return View();
        }

        [HttpPost]
        public ActionResult Estado_Bus()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Estado_Bus_consulta(CC_BUSES model, string direccion, int? km, string latitud, string longitud)
        {
            string usuario = "";
            if (Session["user_login"] == null)
            {
                return View("../Home/Sistemas");
            }
            else
            {
                usuario = Session["user_login"].ToString();

            }

            if (latitud == "" && longitud == "")
            {
                ViewBag.GPS = "Debe Activar GPS";
                List<CC_CONDUCTORES> lista = _BusesLN.Listar_Placa();

                ViewBag.lista = new SelectList(lista, "PLACA", "PLACA");
                ConductoresModel modelo_c = new ConductoresModel();

                DateTime fecha_Actual = DateTime.Now;
                string fecha_nombre = fecha_Actual.ToString("dd/MM/yyyy");
                string hora_actual = fecha_Actual.ToString("HH:mm:ss");

                ViewBag.fecha_actual = fecha_nombre;
                ViewBag.Hora_actual = hora_actual;
                return View("Fuera_Campo");
            }

            var Lista_Dentro_vehiculo = _BusesLN.Lista_Conceptos_Dentro();
            var Lista_Exterior_Vehiculo = _BusesLN.Lista_Conceptos_Exterior();
            var Lista_Cabina_Vehiculo = _BusesLN.Lista_Cabina_Vehiculo();


            BusesModel modelo_buses = new BusesModel();
            try
            {
                var data13 = _BusesLN.Estado_Vigencias(model);
            }
            catch (Exception)
            {
                ViewBag.Message = "Ingrese Placa";
                List<CC_CONDUCTORES> lista = _BusesLN.Listar_Placa();
                ViewBag.lista = new SelectList(lista, "PLACA", "PLACA");
                ConductoresModel modelo_c = new ConductoresModel();

                DateTime fecha_Actual = DateTime.Now;
                string fecha_nombre = fecha_Actual.ToString("dd/MM/yyyy");
                string hora_actual = fecha_Actual.ToString("HH:mm:ss");

                ViewBag.fecha_actual = fecha_nombre;
                ViewBag.Hora_actual = hora_actual;
                return View("Fuera_Campo");
            }
            var vigencias_autos = _BusesLN.Estado_Vigencias(model);

            //LOGICA DE VIGENCIA
            DateTime fecha = DateTime.Now;
            string fecha_ = fecha.ToString("dd/MM/yyyy");



            string mensaje = "";

            //if (vigencias_autos.BS_CVS_FEC_FIN != null &&
            //    //vigencias_autos.COD_CAC != null &&
            //    vigencias_autos.BS_RTV_FIN  != null &&
            //    vigencias_autos.BS_SOAT_FEC_FIN != null &&
            //    //vigencias_autos.RC_FIN != null &&
            //    vigencias_autos.BS_VEHICULOS_FIN != null)
            //{

            //    if (Convert.ToDateTime(vigencias_autos.BS_CVS_FEC_FIN) < Convert.ToDateTime(fecha_) ||
            //        //Convert.ToDateTime(vigencias_autos.COD_CAC) < Convert.ToDateTime(fecha_) ||
            //        Convert.ToDateTime(vigencias_autos.BS_RTV_FIN) < Convert.ToDateTime(fecha_) ||
            //        Convert.ToDateTime(vigencias_autos.BS_SOAT_FEC_FIN) < Convert.ToDateTime(fecha_) 
            //        //|| Convert.ToDateTime(vigencias_autos.RC_FIN) < Convert.ToDateTime(fecha_) 
            //        || Convert.ToDateTime(vigencias_autos.BS_VEHICULOS_FIN) < Convert.ToDateTime(fecha_))
            //    {
            //        mensaje = "NO PROGRAMABLE";
            //    }
            //    else
            //    {
            //        mensaje = "PROGRAMABLE";

            //    }
            //}





            string[] vigencias = new string[] { vigencias_autos.BS_CVS_FEC_FIN, vigencias_autos.COD_CAC, vigencias_autos.BS_RTV_FIN, vigencias_autos.BS_SOAT_FEC_FIN, vigencias_autos.BS_RC_FIN, vigencias_autos.BS_VEHICULOS_FIN };
            ViewBag.vigencias = vigencias;

            modelo_buses.Lista_Dentro_Vehiculo = Lista_Dentro_vehiculo;
            modelo_buses.Lista_Exterior_Vehiculo = Lista_Exterior_Vehiculo;
            modelo_buses.Lista_Cabina_Vehiculo = Lista_Cabina_Vehiculo;


            modelo_buses.CC_BUSES = vigencias_autos;

            ViewBag.direccion = direccion;
            ViewBag.km = km;
            ViewBag.placa = vigencias_autos.BS_PLACA;
            ViewBag.concesionario = vigencias_autos.BS_NOM_EMPRE;
            ViewBag.latitud = latitud;
            ViewBag.longitud = longitud;
            ViewBag.Estado = "PROGRAMABLE";




            return View("Estado_Bus", modelo_buses);
        }


        [HttpPost]
        public ActionResult Insertar_Buses_Despacho(int[] Conceptos, string[] estado, string[] calidad, string[] observacion, string placa, string Concesionario, int? km, string direccion, string longitud, string latitud, HttpPostedFileBase Foto_Cargar1, HttpPostedFileBase Foto_Cargar2, HttpPostedFileBase Foto_Cargar3, HttpPostedFileBase Foto_Cargar4, string mensaje, string comentario)
        {
            string usuario = "";
            if (Session["user_login"] == null)
            {
                return View("../Home/Sistemas"); 
            }
            else
            {
                usuario = Session["user_login"].ToString();
            }

            List<BUSES_DESPACHO> lista = new List<BUSES_DESPACHO>();
            int a = 0;
            int id = 0;
            int codigo_archivo = 0;
            DateTime fecha_Actual = DateTime.Now;
            string fecha_Busqueda = fecha_Actual.ToString("dd/MM/yyyy hh:mm:ss ");
            string codigo_seudonimo = fecha_Actual.ToString("dd-MM-yyyy");



            /*CODIGO ALETORIO */


            try
            {
                var Ultimo_Codigo_Archivo = _BusesLN.Ultimo_Codigo_Archivo(placa);
                codigo_archivo = Ultimo_Codigo_Archivo.BD_COD_DESPACHO + 1;
            }
            catch (Exception)
            {
                codigo_archivo = 0001;
            }


            try
            {
                var id1 = _BusesLN.Ultimo_Buses_Despacho();
                id = id1.BD_ID;
            }
            catch (Exception)

            {
                id = 0;
            }


            /* IMAGEN */

            string ficheroNombre1 = "";
            string ficheroNombre2 = "";
            string ficheroNombre3 = "";
            string ficheroNombre4 = "";


            string urlArchivos = "~/Util/img_despacho";

            if (Foto_Cargar1 != null && Foto_Cargar2 == null && Foto_Cargar3 == null && Foto_Cargar4 == null)
            {
                ficheroNombre1 = "000" + codigo_archivo + "-1" + placa + "." + Path.GetFileName(Foto_Cargar1.ContentType);
                string r1 = Path.Combine(Server.MapPath(urlArchivos), ficheroNombre1);
                Foto_Cargar1.SaveAs(r1);
            }
            if (Foto_Cargar1 != null && Foto_Cargar2 != null && Foto_Cargar3 == null && Foto_Cargar4 == null)
            {
                ficheroNombre1 = "000" + codigo_archivo + "-1" + placa + "." + Path.GetFileName(Foto_Cargar1.ContentType);
                string r1 = Path.Combine(Server.MapPath(urlArchivos), ficheroNombre1);
                Foto_Cargar1.SaveAs(r1);

LOGINPUA/LOGINPUA/Views/Supervisor/Fuera_Campo.cshtml
@model LOGINPUA.Models.ConductoresModel

@{
    ViewBag.Title = "Fuera_Campo";
    Layout = "~/Views/Shared/_LayoutInicial.cshtml";
}
<style>
    .center {
        margin: auto;
        width: 80%;
        padding: 10px;
    }
</style>

<br />




<div class="row">
    <div class="col-md-12 text-center">
        <h4>
            Registro de Supervision en Campo
        </h4>
    </div>
</div>
<hr />
@using (Html.BeginForm("Estado_Bus_consulta", "Supervisor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="modal-body ">

        <div class="center">

            <br />

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group row">
                        <h2 class="col-sm-4 col-form-label">Placas</h2>
                        <div class="col-sm-5">
                            @Html.DropDownListFor(model => model.CC_CONDUCTORES.PLACA, ViewBag.lista as SelectList, "Ingresar PLACA", new { Name = "BS_PLACA", @class = "selectpicker", @data_live_search = "true", @data_style = "btn-info", style = "width: 160%;" })
                        </div>

                    </div>
                </div>


                <div class="col-md-4">
                    <div class="form-group row">
                        <h2 class="col-sm-3 col-form-label">Fecha</h2>
                        <div class="col-sm-8">
                            <input type="text" name="name" value="@ViewBag.fecha_actual" class="form-control" disabled />
                        </div>

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group row">
                        <h2 class="col-sm-3 col-form-label">Hora</h2>
                        <div class="col-sm-8">
                            <input type="datetime" name="name" value="@ViewBag.Hora_actual" class="form-control" disabled>
                        </div>

                    </div>
                </div>
            </div>
            <br />            <br />


            <div class="row">

                 <div class="col-md-6">
                    <div class="form-group row">
                        <h2 class="col-sm-4 col-form-label">Dirección de inspección</h2>
                        <div class="col-sm-7">
                            <select name="direccion" value="" class="form-control vacios" style="width:100%;" required>
                                <option value="CANTA CALLAO (SAN MARTIN) A-B">CANTA CALLAO (SAN MARTIN) A-B</option>
                                <option value="TRISTAN (SURCO) B-A">TRISTAN (SURCO) B-A</option>
                                <option value="CERES (ATE) A-B">CERES (ATE) A-B</option>
                                <option value="LA MARINA(SAN MIGUEL) B-A">LA MARINA(SAN MIGUEL) B-A</option>
                                <option value="SANTA MARIA (LA MOLINA)">SANTA MARIA (LA MOLINA) </option>
                                <option value="MOLICENTRO (LA MOLINA) A-B">MOLICENTRO (LA MOLINA) A-B</option>
                                <option value="HONDA (SAN MIGUEL) B-A">HONDA (SAN MIGUEL) B-A</option>
                                <option value="MUSA (LA MOLINA) A-B">MUSA (LA MOLINA) A-B</option>
                                <option value="MASIAS (SAN ISIDRO) B-A">MASIAS (SAN ISIDRO) B-A</option>
                                <option value="SANTA MARIA (LA MOLINA) A-B">SANTA MARIA (LA MOLINA) A-B</option>
                                <option value="TAGORE (ATE) A-B">TAGORE (ATE) A-B</option>
                                <option value="SAN MARCOS (SAN MIGUEL) B-A">SAN MARCOS (SAN MIGUEL) B-A</option>
                                <option value="FUERTE HOYOS (RIMAC) A-B">FUERTE HOYOS (RIMAC) A-B</option>
                                <option value="PLAZA BUTTERS B-A">PLAZA BUTTERS B-A</option>
                                <option value="CAJA DE AGUA (RIMAC) A-B">CAJA DE AGUA (RIMAC) A-B</option>
                                <option value="PARDO (MIRAFLORES) B-A">PARDO (MIRAFLORES) B-A</option>
                                <option value="FLOR DE AMANCAES (RIMAC) A-B">FLOR DE AMANCAES (RIMAC) A-B</option>
                                <option value="OLAVIDE (SAN ISIDRO) B-A">OLAVIDE (SAN ISIDRO) B-A</option>
                                <option value="PATIO SANTA CATALINA (SJL) A-B">PATIO SANTA CATALINA (SJL) A-B</option>
                                <option value="VENUS (MARDALENA DEL MAR) B-A">VENUS (MARDALENA DEL MAR) B-A</option>
                                <option value="PATIO PROCERES (SJL) A-B">PATIO PROCERES (SJL) A-B</option>
                                <option value="TORRE UGARTE B-A">TORRE UGARTE B-A</option>
                                <option value="PATIO NUEVA ALTERNATIVA A-B">PATIO NUEVA ALTERNATIVA A-B</option>
                                <option value="NAVARRETE (SAN ISIDRO) B-A">NAVARRETE (SAN ISIDRO) B-A</option>
                                <option value="PATIO FUTURO EXPRESS (SJL) A-B">PATIO FUTURO EXPRESS (SJL) A-B</option>
                                <option value="ICA (CERCADO DE LIMA) B-A">ICA (CERCADO DE LIMA) B-A</option>
                                <option value="GRAU (CERCADO DE LIMA) A-B">GRAU (CERCADO DE LIMA) A-B</option>
                                <option value="FAUCETT (SAN MIGUEL) B-A">FAUCETT (SAN MIGUEL) B-A</option>
                            </select>
                        </div>

                    </div>
                </div>


                <div class="col-md-5">
                    <div class="form-group row">
                        <h2 class="col-sm-2 col-form-label">Km</h2>
                        <div class="col-sm-6">
                            <input type="text" name="km" value="" class="form-control" />
                        </div>

                    </div>
                </div>

            </div>
            <br />            <br />
            <div class="row">
                <div class="col-md-5"></div>

                <div class="col-md-6">
                    <input type="submit" name="name" value="Generar" id="validacion_v" class="btn btn-success btn-lg" />
                </div>
            </div>

            <input type="text" class="latitud" name="latitud" hidden>
            <input type="text" class="longitud" name="longitud" hidden>
        </div>

    </div>
}






@if (@ViewBag.Message == "Ingrese Placa")
{
    <script>
        var closable = alertify.alert().setting('closable');
        alertify.alert()
         .setting({
             'label': 'Cerrar',
             'message': 'Ingresar Placa' + (closable ? ' ' : ' not ') + '',
             'onok': function () {
                 ;
             }
         }).show();
    </script>
}

@if (@ViewBag.GPS == "Debe Activar GPS")
{
    <script>
        var closable = alertify.alert().setting('closable');
        alertify.alert()
         .setting({
             'label': 'Cerrar',
             'message': 'Debe Activar GPS' + (closable ? ' ' : ' not ') + '',
             'onok': function () {
                 ;
             }
         }).show();
    </script>
}


<script>

    $(document).ready(function () {
        $(".bs-placeholder").css("width", "136%")
        console.log($('#CC_CONDUCTORES_PLACA').siblings('button'))
         

    });
     

    function myFunction() {
        var a = document.getElementById("latitud");
        var b = document.getElementById("longitud");

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
        
        function showPosition(position) {
            document.querySelector('.latitud').defaultValue = position.coords.latitude;
            document.querySelector('.longitud').defaultValue = position.coords.longitude;

        }
    }
    window.onload = myFunction();
    $('#validacion_v').click(function (event) {
        var bool = $('.vacios').toArray().some(function (el) {
            return $(el).val().length < 1;
        });

        var documento = $('#vacio').val();
        if (bool) {
            alertify
              .alert("Completar los campos faltantes", function () {
              });
            event.preventDefault();
        }
    });

    $(document).ajaxStart(function () {

    }).ajaxStop(function () {
        $('#validacion_v').prop('disabled', true).html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>Guardando...');
    });
 

</script>

LOGINPUA/LOGINPUA/Views/Supervisor/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_corredores_Supervisor.cshtml";
}

 