LOGINPUA/LOGINPUA/Controllers/BusesController.cs
using ENTIDADES;
using LN.EntidadesLN;
using LOGINPUA.Models;
using LOGINPUA.Repositorio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LOGINPUA.Controllers
{
    public class BusesController : Controller
    {

        private readonly PerfilLN _PerfilLN;
        Util.Util utilidades = new Util.Util();

        private readonly LoginLN _LoginLN;
        private readonly RutaLN _rutaLN;
        private readonly CorredoresLN _CorredoresLN;
        private readonly BUSESLN _BusesLN;
        private readonly AccesoLN _AccesoLN;
        private readonly AccEmpLN _AccEmpLN;
        public BusesController(LoginLN LoginLN, AccesoLN AccesoLN, AccEmpLN AccEmpLN, BUSESLN BusesLN, CorredoresLN CorredoresLN)
        {
            _LoginLN = LoginLN;
            _AccesoLN = AccesoLN;
            _AccEmpLN = AccEmpLN;
            _BusesLN = BusesLN;
            _CorredoresLN = CorredoresLN;
        }
        ReadExcel readExcel = new ReadExcel();

        public ActionResult Buses()
        {
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                return View();
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }

        }
        public ActionResult Buses_Desafectados(int? id_bus_desafec,string ObservacionBus)
        {
            if (id_bus_desafec != null)
            {
                ViewBag.placa_desafec = id_bus_desafec;
                 
            }
            return View();
        }
 
        public string getRutaCorredor()
        {
            var lista = _CorredoresLN.getRutaCorredor();
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string ListarBuses()
        {
            var lista = _BusesLN.Listar_Buses();
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string ListarBusesbyId(int idCorredor)
        {
            var lista = _BusesLN.Listar_Buses_by_Id(idCorredor);
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string Subir_Excel()
        {
            //RPTA_GENERAL e = new RPTA_GENERAL();
            RPTA_GENERAL rpta = new RPTA_GENERAL();

            RegistroPicoPlacaLN _registroPicoPlacaLN = new RegistroPicoPlacaLN();

            var data = "";
            string usuario = Session["user_login"].ToString();
            var ob = Request.Files;
            var archivoSubido = Request.Files[0];
            var nombreArchivo = Path.GetFileName(archivoSubido.FileName);
            var extensionArchivo = Path.GetExtension(archivoSubido.FileName);
            var arrFileName = nombreArchivo.Split('.');
            var nuevoNombreArchivoExcel = arrFileName[0] + "_FILE_" + DateTime.Now.ToString("dd_MM_yyyy_h_mm_ss") + extensionArchivo;
            var pathArchivo = Server.MapPath("~/Adjuntos/Files_Despacho/" + nuevoNombreArchivoExcel);
            string pathFinal = Path.Combine(pathArchivo);
            archivoSubido.SaveAs(pathFinal);

            data = readExcel.Matriz_Placas(pathFinal, usuario);

            return data;
        }


        public string Registro_Bus_Indiv(CC_BUSES Model_Bus)
        {
            RPTA_GENERAL r = new RPTA_GENERAL();
            var result = "";
            //Validar si Existe la placa
            var rpt_placa = _BusesLN.Verifica_Placa_Existente(Model_Bus.BS_PLACA);

            if (rpt_placa.AUX == 0)
            {

                string usuario = Session["user_login"].ToString();
                Model_Bus.ID_ESTADO = 1;
                Model_Bus.USU_REG = usuario;
                Model_Bus.ESTADO_VEHICULO = "NORMAL";

                var data = _BusesLN.Insertar_Buses_Nuevos(Model_Bus);
                result = JsonConvert.SerializeObject(data);
            }
            else
            {
                r.COD_ESTADO = 0;
                r.DES_ESTADO = "Placa Existente";
                result = JsonConvert.SerializeObject(r);
            }
            return result;
        }

        public string anularBus(int idBus)
        {
            var anularBus = JsonConvert.SerializeObject(_BusesLN.anularBus(idBus, Session["user_login"].ToString()));
            return anularBus;
        }

        public string Modificar_Bus(CC_BUSES Model_Bus)
        {
            string usuario = Session["user_login"].ToString();

            Model_Bus.USU_MODIF = usuario;


            var data = _BusesLN.Modificar_Bus(Model_Bus);
            var result = JsonConvert.SerializeObject(data);
            return result;
        }

        public string listarBusesDesafectados()
        {
            var lista = _BusesLN.Listar_Buses_Desafectados();
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string Registro_Bus_Afectado(CC_BUSES Model_Bus, int id_placa_reemplazada)
        {
            string usuario = Session["user_login"].ToString();
            Model_Bus.ID_ESTADO = 1;
            Model_Bus.USU_REG = usuario;
            Model_Bus.ESTADO_VEHICULO = "NORMAL";


            var data = _BusesLN.Insertar_Buses_Afectados(Model_Bus);

            //PLACA NUEVA DEL BUS
            var placa_nueva = data.DES_ESTADO;
            var datas = _BusesLN.desafectarBus(id_placa_reemplazada, placa_nueva);
            var result = JsonConvert.SerializeObject(datas);
            return result;
        }
    }

}

LOGINPUA/LOGINPUA/Controllers/IncidenciasController.cs
using ENTIDADES;
using LN.EntidadesLN;
using LOGINPUA.Models;
using LOGINPUA.Repositorio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LOGINPUA.Controllers
{
    public class IncidenciasController : Controller
    {

        private readonly PerfilLN _PerfilLN;
        Util.Util utilidades = new Util.Util();

        private readonly LoginLN _LoginLN;
        private readonly RutaLN _rutaLN;
        private readonly CorredoresLN _CorredoresLN;
        private readonly IncidenciasLN _IncidenciasLN;
        private readonly AccesoLN _AccesoLN;
        private readonly AccEmpLN _AccEmpLN;
        public IncidenciasController(LoginLN LoginLN, AccesoLN AccesoLN, AccEmpLN AccEmpLN, IncidenciasLN IncidenciasLN, RutaLN RutaLN,CorredoresLN CorredoresLN)
        {
            _LoginLN = LoginLN;
            _rutaLN = RutaLN;
            _AccesoLN = AccesoLN;
            _AccEmpLN = AccEmpLN;
            _IncidenciasLN = IncidenciasLN;
            _CorredoresLN = CorredoresLN;
        }
        ReadExcel readExcel = new ReadExcel();

        public ActionResult Incidencias()
        {
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                var datosCorredores = _CorredoresLN.obtenerListaCorredores();
                ViewBag.rutas = _rutaLN.getRutaCorredor();
                ViewBag.corredores = JsonConvert.SerializeObject(datosCorredores);

                ViewBag.Accionesview = Lista_acciones;
                return View(_CorredoresLN.obtenerListaCorredores());
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
        }

        public string Listar_Incidencias()
        {
            var lista = _IncidenciasLN.Listar_Incidencias();
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string Registrar_Incidencia(CC_INCIDENCIA Model_Incidencia)
        {
            RPTA_GENERAL r = new RPTA_GENERAL();
            var result = "";

            string usuario = Session["user_login"].ToString();
            Model_Incidencia.ID_ESTADO = 1;
            Model_Incidencia.USU_REG = usuario;
            Model_Incidencia.ID_RUTA = 1;

            var data = _IncidenciasLN.Registrar_Incidencia(Model_Incidencia);
            result = JsonConvert.SerializeObject(data);


            return result;
        }

        public string AnularIncidencia(int idIncidencia)
        {
            var anularBus = JsonConvert.SerializeObject(_IncidenciasLN.AnularIncidencia(idIncidencia, Session["user_login"].ToString()));
            return anularBus;
        }




        public ActionResult Infracciones()
        {
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();

            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                return View();
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }


        }

        public string Listar_Infracciones()
        {
            var lista = _IncidenciasLN.Listar_Infracciones();
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string Listar_Persona_Incidencia()
        {
            var lista = _IncidenciasLN.Listar_Persona_Incidencia();
            var result = JsonConvert.SerializeObject(lista); //para la lista principal
            return result;
        }

        public string Registrar_Infraccion(CC_INFRACCION Model_Infraccion)
        {
            RPTA_GENERAL r = new RPTA_GENERAL();
            var result = "";

            string usuario = Session["user_login"].ToString();
            Model_Infraccion.ID_ESTADO = 1;
            Model_Infraccion.USU_REG = usuario;

            Model_Infraccion.MULTA_UIT = Model_Infraccion.MULTA_UIT + "%";
            Model_Infraccion.MONTO_MULTA = "S/. "+ Model_Infraccion.MONTO_MULTA;

            var data = _IncidenciasLN.Registrar_Infraccion(Model_Infraccion);
            result = JsonConvert.SerializeObject(data);

            
            return result;
        }

        public string Editar_Infraccion(CC_INFRACCION Model_Infraccion)
        {
            string usuario = Session["user_login"].ToString();

            Model_Infraccion.USU_MODIF = usuario;


            var data = _IncidenciasLN.Editar_Infraccion(Model_Infraccion);
            var result = JsonConvert.SerializeObject(data);
            return result;
        }


    }

}

LOGINPUA/LOGINPUA/Views/Incidencias/Incidencias.cshtml
@{
    ViewBag.Title = "Conductores";
    Layout = "~/Views/Shared/_LayoutInicial.cshtml";

    List<ENTIDADES.CC_MENUPERFIL_ACCION> Lista_acciones = ViewBag.Accionesview as List<ENTIDADES.CC_MENUPERFIL_ACCION>;
    int ideliminar = 0;
    int idmodificar = 0;

    List<ENTIDADES.CC_RUTA_CORREDOR> listRutas = new List<ENTIDADES.CC_RUTA_CORREDOR>();
    listRutas = ViewBag.rutas;
}

<style>
    body {
        overflow-x: scroll;
    }



    .textoAchicado {
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        max-width: 163px;
    }
</style>

<script src="~/Content/js/js_incidencias/js_registro_incidencias.js"></script>



<div class="row">
    <div class="col-md-12 text-center">
        <br />
        <h4>

            Incidencias &nbsp;&nbsp;&nbsp;


            @foreach (var item in Lista_acciones)
            {
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.REGISTRAR.ToString()) //cambiar a enumerado
                {
                    <a href="" id="btnRegistrarIncidencia" class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal_agregar_inciden">
                        <span class="fa fa-plus"></span>
                    </a>
                }

                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.MODIFICAR.ToString())
                {
                    idmodificar = 1;
                    <input type="text" id="permisoActualiza" value="1" hidden />
                }
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.ANULAR.ToString())
                {
                    ideliminar = 1;
                    <input type="text" id="permisoEliminar" value="1" hidden />
                }
            }



            <button type="button" class="btn btn-info btn-sm" id="btnBusquedaEnTabla">
                <span class="fa fa-search"></span>
            </button>

        </h4>
    </div>
</div>



<br />
<div class="row">
    <div class="col-md-2">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" title="Corredor"><span class="far fa-hospital" aria-hidden="true"></span></span>
            </div>
            @*<select class="form-control form-control-sm" id="selectCorredores" onchange="getRutaPorCorredor();"></select>*@
            <select class="form-control form-control-sm" id="selectCorredores" onchange="getRutaPorCorredor();"><option value="2">JP</option><option value="5">PN</option><option value="4">SJL</option><option value="3">CC</option><option value="1">TGA</option></select>
        </div>
    </div>

    <div class="col-md-2">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" title="Ruta"><span class="fas fa-road" aria-hidden="true"></span></span>
            </div>
            <select class="form-control form-control-sm" id="selectRutaCorredor"><option value="12">202</option><option value="13">206</option><option value="14">257</option><option value="15">209</option><option value="2">201</option><option value="244">204</option><option value="401">250</option></select>

            @*<select class="form-control form-control-sm" id="selectRutaCorredor">*@
                @*@foreach (var item in listRutas)
                    {
                        <option value="@item.ID_RUTA">@item.ABREV_CORREDOR   @item.NRO_RUTA</option>

                    }*@
            @*</select>*@

        </div>
    </div>

    <select class="form-control form-control-sm" id="selectCorredores" hidden>
        @foreach (var item in Model)
            {
            <option value="@item.ID_CORREDOR">@item.ABREVIATURA</option>
        }
    </select>






    @*<div class="col-md-2">
            <div class="col-xs-6">
                <button class="btn btn-info btn-sm" id="mostrartodo_btn" onclick="getListBuses();"><i class="fas fa-bus-alt"></i>&nbsp; Mostrar Todo</button>
            </div>
        </div>*@

    @*<div class="col-md-1" style="display: none">
            <button id="consultar" class="btn btn-info btn-sm" data-toggle="modal" style="text-transform: capitalize;" onclick="getListConductores();">Consultar</button>

        </div>

        <div class="col-md-2" style="display: none">
            <div class="col-xs-6">

            </div>
        </div>
        <div class="col-md-8 text-right">
            <button id="exportar" class="btn btn-success btn-sm" data-toggle="modal" style="text-transform: capitalize;" onclick="exportarTabla();">Exportar</button>
        </div>*@



</div>
<hr />

<div class="row">
    <div class="col-sm-12">
        <div>

            <table class="responsive-table" id="Tbincidencias" style="width:100%">
                <thead class="thead-azul-claro">
                    <tr>
                        <th>N°</th>



                        <th>FECHA</th>
                        <th>HORA</th>
                        <th>PLACA</th>
                        <th>OPERADOR</th>
                        <th>INFRACCION</th>
                        <th>SANCION</th>
                        <th>DESCRIPCION</th>
                        <th>DESCARGO</th>
                        <th>USU REG</th>
                        <th>FECHA REG</th>
                        @*@if (idmodificar == 1)
                            {
                                <th style="width: 100px;color:#1d96b2">aS</th>
                                <th style="width: 100px;color:#1d96b2">aS</th>
                            }*@
                        @if (ideliminar == 1)
                        {
                            <th style="color:#1d96b2"></th>
                        }

                    </tr>
                </thead>
                <tbody class="display nowrap" id="listar_incidencias">
                    @*<tr>
                        <td colspan="13">Cargando informacion de las Incidencias correspondientes</td>
                    </tr>*@
                </tbody>
            </table>
        </div>

    </div>
</div>

@Html.Partial("_AgregarIncidencia")
@Html.Partial("_EditarIncidencia")



<script>
    var Utilidades = new Util();


    var URL_LIST_CONDUCTORES = "@Url.Action("ListarConductores", "Conductores")";
    var URL_LIST_PERSONA_INCIDENCIA = "@Url.Action("Listar_Persona_Incidencia", "Incidencias")";
    var URL_LIST_INCIDENCIAS = "@Url.Action("Listar_Incidencias", "Incidencias")";
    var URL_LIST_INFRACCIONES = "@Url.Action("Listar_Infracciones", "Incidencias")";
    var URL_REGISTRAR_INCIDENCIA = "@Url.Action("Registrar_Incidencia", "Incidencias")";
    var URL_ANULA_INCIDENCIA = "@Url.Action("AnularIncidencia", "Incidencias")";
    var URL_GET_RUTA_X_CORREDOR = "@Url.Action("getRutaxCorredor", "Programacion")";
    var URL_GET_TIPOOPER_X_RUTA = "@Url.Action("getTiposServicioByIdRuta", "RutaTipoServicio")";

    @*var URL_LIST_CORREDORES = "@Url.Action("getRutaCorredor", "Buses")";
    var URL_LIST_BUSES_BY_ID = "@Url.Action("ListarBusesbyId", "Buses")";
    var URL_ACTION_UPLOAD_FILE = "@Url.Action("Subir_Excel", "Buses")";
    var URL_REGISTRAR_BUS_INDIV = "@Url.Action("Registro_Bus_Indiv", "Buses")";
    var URL_ANULA_BUS = "@Url.Action("anularBus", "Buses")";
    var URL_MODIFICA_BUS = "@Url.Action("Modificar_Bus", "Buses")";
    var FECHA_HOY = '@DateTime.Now.ToString("dd/MM/yyyy")';
    var URL_GET_PLACA_DESAFECT = "@Url.Action("Buses_Desafectados", "Buses")";*@



    //$('#txtFechaRegistro').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro1').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro2').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro3').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro4').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro5').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro6').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro7').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro8').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro9').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro10').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro11').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro12').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro13').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro14').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro15').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro16').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro17').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro18').datepicker({ format: "dd/mm/yyyy" });
    //$('#txtFechaRegistro19').datepicker({ format: "dd/mm/yyyy" });
        @{ HtmlString dataCorredores = new HtmlString(ViewBag.corredores); }
    var JSON_DATA_CORREDORES = JSON.parse('@dataCorredores');


</script>

LOGINPUA/LOGINPUA/Views/Incidencias/_AgregarInfraccion.cshtml
<div class="modal fade" id="modal_agregar_infracc">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" style="width:600px;margin-left:200px;">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Registro Infraccion</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>

                </button>

            </div>
            <form id="sectionParametrosAgregarInfraccion" autocomplete="off">
                <div class="modal-body" style="padding-left: 45px; padding-right: 0px;">

                    <div class="form-group  col-md-6" style="display:none">
                        <div>
                            <input name="ID_INFRACCION" class="form-control" id="" style="display:unset;width:80% ">
                        </div>

                    </div>


                    <div class="control-group">
                        <div class="form-group row">
                            <div class="form-group  col-md-6">
                                <label>PERSONA DE LA INCIDENCIA</label>
                                <div>
                                    <select name="ID_PERSONA_INCIDENCIA" class="form-control" id="selectAgregarPersonaIncidencia" style="display:unset;width:80% "></select>
                                </div>
                            </div>

                            <div class="form-group  col-md-6">
                                <label>CODIGO DE INFRACCION</label>
                                <div>
                                    <input required name="COD_INFRACCION" class="form-control" id="" style="display:unset;width:80% ">
                                </div>
                            </div>

                        </div>
                    </div>



                    <div class="control-group">
                        <div class="form-group row">

                            <div class="form-group  col-md-6">
                                <label>CALIFICACION</label>
                                <div class="">
                                    <select  name="CALIFICACION" style="display:unset;width:80%" type="text" class="form-control">
                                        <option value="Leve">LEVE</option>
                                        <option value="Grave">GRAVE</option>
                                        <option value="Muy Grave">MUY GRAVE</option>
                                    </select>
                                    @*<input name="CALIFICACION" id="" style="display:unset;width:80%" type="text" class="form-control">*@
                                </div>
                            </div>

                            <div class="form-group  col-md-6">
                                <label>MULTA EN UIT (%)</label>
                                <div class="">
                                    <input required name="MULTA_UIT" id="" style="display:unset;width:80%" type="number" class="form-control">
                                </div>
                            </div>

                        </div>
                    </div>



                    <div class="control-group">
                        <div class="form-group row">
                            <div class="form-group  col-md-6">
                                <label>MONTO DE LA MULTA (S/.)</label>
                                <div class="">
                                    <input required name="MONTO_MULTA" id="" style="display:unset;width:80%" type="number" class="form-control">
                                </div>
                            </div>


                            <div class="form-group col-md-6">

                                <label>TIPO_INFRACCION</label>
                                <div class="">
                                    <input required name="TIPO_INFRACCION" id="" style="display:unset;width:80%" type="text" class="form-control">
                                </div>

                            </div>

                        </div>
                    </div>

                    <div class="control-group">
                        <div class="form-group row">

                            <div class="form-group col-md-6">

                                <label>DESCRIPCION</label>
                                <div class="">
                                    <textarea required name="DESCRIPCION" id="" style="display:unset;width:80%;height: 200px;" type="text" class="form-control"></textarea>
                                </div>

                            </div>


                            <div class="form-group  col-md-6">
                                <label>SANCION</label>
                                <div class="">
                                    <textarea required name="SANCION" id="" style="display:unset;width:80%;height: 200px;" type="text" class="form-control"></textarea>
                                </div>
                            </div>


                        </div>
                    </div>


                </div>



                <div class="modal-footer">
                    <button id="registrar_infrac_btn" class="btn btn-info" type="submit">Guardar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>

    </div>
</div>