LOGINPUA/LOGINPUA/Controllers/Proveedor_ServicioController.cs
using ENTIDADES;
using LN.EntidadesLN;
using LOGINPUA.Util.Seguridad;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LOGINPUA.Controllers
{
    public class Proveedor_ServicioController : Controller
    {
        // GET: Proovedor_Servicio
        private readonly Proveedor_ServLN _Proveedor_ServLN;
        private readonly Usuario_PersonaLN _Usuario_PersonaLN;
        Util.Util utilidades = new Util.Util();

        public Proveedor_ServicioController(Proveedor_ServLN Proveedor_ServLN, Usuario_PersonaLN Usuario_PersonaLN)
        {
            _Proveedor_ServLN = Proveedor_ServLN;
            _Usuario_PersonaLN = Usuario_PersonaLN;
        }

        public ActionResult Inicio()
        {
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();
            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                var listaUsuario = _Proveedor_ServLN.ListarUsuarios();
                ViewBag.listaUsuario = listaUsuario;
                return View();
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
        }


        public string Desactivar_Cuenta_Usuario(int id_prov_usuario)
        {
            string usuario = Session["user_login"].ToString();
            var rpta = _Proveedor_ServLN.Desactivar_Cuenta_Usuario(id_prov_usuario, usuario);
            var result = JsonConvert.SerializeObject(rpta);
            return result;
        }
        public string Actualizar_ContraseñaAnti(int id_prov_usuario)
        {
            var rpta = _Proveedor_ServLN.Actualizar_ContraseñaAnti(id_prov_usuario);
            var result = JsonConvert.SerializeObject(rpta);
            return result;
        }


        public string Desactivar_ProvUsuarios(int idusuario)
        {
            string usuario = Session["user_login"].ToString();
            var rpta = _Proveedor_ServLN.Desactivar_ProvUsuarios(idusuario, usuario);
            var result = JsonConvert.SerializeObject(rpta);
            return result;
        }


        public string ListarProvee_Serv()
        {

            var listar = _Proveedor_ServLN.ListarProveedorServ();
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }
        public string ListCorredores(int id_prov_serv)
        {


            var listar = _Proveedor_ServLN.ListCorredores(id_prov_serv);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }

        public string ListCorredor_X_Usuprov(int id_prov_usu)
        {
            var listar = _Proveedor_ServLN.ListCorredor_X_Usuprov(id_prov_usu);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }


        public string ListarProvServ_Usuario()
        {
            var listar = _Proveedor_ServLN.ListarProvServ_Usuario();
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }

        public string AgregarUsuario_Proveedor(int idprov, string usuario, string contraseña)
        {
            var result = "";
            string usuario_session = Session["user_login"].ToString();

            var rpta_FINAL = _Proveedor_ServLN.Rpta_Cuenta_Existente(idprov, usuario);

            if (rpta_FINAL.AUX == 1)
            {
                rpta_FINAL.DES_ESTADO = "Usuario Existente";
                rpta_FINAL.COD_ESTADO = 0;
                result = JsonConvert.SerializeObject(rpta_FINAL); //para la lista principal
            }
            else
            {
                var rpta = _Proveedor_ServLN.AgregarUsuario_Proveedor(idprov, usuario, contraseña, usuario_session);
                result = JsonConvert.SerializeObject(rpta); //para la lista principal
            }
            return result;
        }

        public string AgregarUsuarios_Corredor(string idcorredores, int idusuario, int id_prov_usuario, int id_prov_serv, int tipo_accion)
        {
            var result = "";
            string[] id_corredor_nuevo = idcorredores.Split('|');
            string usuario_session = Session["user_login"].ToString();

            if (tipo_accion == 0)
            {
                var rpta_FINAL = _Proveedor_ServLN.Rpta_Usuario_Existente(id_prov_usuario, idusuario, id_prov_serv);
                if (rpta_FINAL.AUX == 1)
                {
                    rpta_FINAL.DES_ESTADO = "Usuario Existente";
                    rpta_FINAL.COD_ESTADO = 0;
                    result = JsonConvert.SerializeObject(rpta_FINAL); //para la lista principal

                }
                else
                {
                    _Proveedor_ServLN.Desactivar_Cuenta_Usuario(id_prov_usuario, usuario_session);

                    //ENLAZA EL USUARIO CON LA CUENTA 
                    var rpta = _Proveedor_ServLN.Actualizar_Usuario_Prov(id_prov_usuario, idusuario, usuario_session);

                    //AGREGA NUEVOS CORREDORES CON EL USUARIO 
                    foreach (var idcorredor in id_corredor_nuevo)
                    {
                        int id_corredores_final = Convert.ToInt32(idcorredor);
                        _Proveedor_ServLN.AgregarUsuario_Corredor(id_corredores_final, id_prov_usuario, usuario_session);

                    }
                    //string usuario_session = Session["user_login"].ToString();

                    //var rpta = _Proveedor_ServLN.AgregarUsuario_Proveedor(proveedor, usuario, contraseña, usuario_session);
                    result = JsonConvert.SerializeObject(rpta); //para la lista principal
                }

            }
            else if (tipo_accion == 1)
            {
                _Proveedor_ServLN.Desactivar_Cuenta_Usuario(id_prov_usuario, usuario_session);

                //ENLAZA EL USUARIO CON LA CUENTA 
                var rpta = _Proveedor_ServLN.Actualizar_Usuario_Prov(id_prov_usuario, idusuario, usuario_session);

                //AGREGA NUEVOS CORREDORES CON EL USUARIO 
                foreach (var idcorredor in id_corredor_nuevo)
                {
                    int id_corredores_final = Convert.ToInt32(idcorredor);
                    _Proveedor_ServLN.AgregarUsuario_Corredor(id_corredores_final, id_prov_usuario, usuario_session);

                }
                result = JsonConvert.SerializeObject(rpta); //para la lista principal                
            }
            return result;
        }




        public ActionResult ABEXA(string abrev_corr, string usuario, string contraseña, string url)
        {
            var contraseña_ = contraseña.Replace(' ', '+');

            //Corredor Correspondiente
            string corredorAbexa = "";
            corredorAbexa = usuario + abrev_corr;
            //Concatena datos y encripta
            string concatenado = corredorAbexa + "|" + Encriptador.Desencriptar(contraseña_);
            string codigoConcatenado = Encriptador.Encriptar(concatenado);
            string UrlRedirect = url + codigoConcatenado;
            return Redirect(UrlRedirect);
        }
        public ActionResult MATRIX(string abrev_corr, string usuario, string contraseña, string url)
        {
            //PARA EL ENCRIPTADOR
            string output = "";
            string str = "";

            //var ubijava = @"C:\Program Files\Java\jdk1.8.0_201\bin\";
            var ubiJar = "-jar \"" + Server.MapPath("~/Util/encriptador.jar") + "\" " + abrev_corr + " " + usuario + " " + contraseña;
            try
            {
                var proceso = new Process();
                proceso.EnableRaisingEvents = false;
                proceso.StartInfo.FileName = @"C:\Program Files\Java\jdk1.8.0_201\bin\java.exe";
                proceso.StartInfo.Arguments = ubiJar;
                proceso.StartInfo.UseShellExecute = false;
                proceso.StartInfo.RedirectStandardOutput = true;
                proceso.Start();
                StreamReader reader = proceso.StandardOutput;
                output = reader.ReadToEnd();
                str = output;
                str = str.Remove(str.Length - 2, 2);

                //REDIRECCIONA A MATRIX
                return Redirect("http://www.matrix.pe/matrix/?idEnc=" + str);
            }
            catch (Win32Exception w)
            {
                Console.WriteLine(w.Message);
                Console.WriteLine(w.ErrorCode.ToString());
                Console.WriteLine(w.NativeErrorCode.ToString());
                Console.WriteLine(w.StackTrace);
                Console.WriteLine(w.Source);
                Exception e = w.GetBaseException();
                Console.WriteLine(e.Message);
                return View(e.Message);
            }
        }


    }
}

LOGINPUA/LOGINPUA/Views/Proveedor_Servicio/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
    Layout = "~/Views/Shared/_LayoutInicial.cshtml";

    List<ENTIDADES.CC_MENUPERFIL_ACCION> Lista_acciones = ViewBag.Accionesview as List<ENTIDADES.CC_MENUPERFIL_ACCION>;
    int ideliminar = 0;
    int idmodificar = 0;

}

<script src="~/Content/js/js_mantenimiento_Proveedor_Serv/registro_Proveedor_Serv.js@("?v="+ DateTime.Now.ToString("yyyyMMddhmmss"))"></script>

<style>
    .modal-dialog {
        max-width: max-content !important;
    }

    .modal-content input {
        width: auto !important;
    }

    .modal-content {
        width: 120%;
    }

    .btn-light {
        background-color: white;
        border: 1px solid #ced4da;
    }
</style>
<br />

<h3 class="text-center">
    Mantenimiento Proveedor Servicio

    @foreach (var item in Lista_acciones)
    {
        if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.REGISTRAR.ToString()) //cambiar a enumerado
        {
            <button type="button" id="modal_registroprovserv" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal">
                <span class="fa fa-plus"></span>
            </button>
        }

        if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.MODIFICAR.ToString())
        {
            idmodificar = 1;
            <input type="text" id="permisoActualiza" value="1" hidden />
        }
        if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.ANULAR.ToString())
        {
            ideliminar = 1;
            <input type="text" id="permisoEliminar" value="1" hidden />
        }
    }




    <button type="button" class="btn btn-info btn-sm" id="btnBusquedaEnTabla">
        <span class="fa fa-search"></span>
    </button>
</h3>
<br />
<hr />
<div class="table-responsive">

    <form>
        <table class="responsive-table" id="tbListarProvServ_Usuario" style="width:100%">
            <thead class="thead-azul-claro">
                <tr>
                    <th style="width: 40px;">N°</th>
                    <th class="text-center" style="width: 60px;">USUARIO</th>
                    <th class="text-center" style="width: 60px;">PROVEEDOR</th>
                    <th class="text-center" style="width: 60px;">U.PROVEEDOR</th>
                    <th class="text-center" style="width: 60px;">CONTRASEÑA</th>

                    <th class="text-center" style="width: 70px;">USU_REG</th>
                    <th style="width: 115px;">FECHA_REG</th>
                    @if (idmodificar == 1)
                    {
                        <th class="text-center" style="width:50px;"></th>
                        <th class="text-center" style="width:50px;"></th>
                    }
                    @if (ideliminar == 1)
                    {
                        <th class="text-center" style="width:50px;"></th>
                    }

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="13" class="text-center">No Existe Información.</td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
@Html.Partial("_RegistroProv_Serv")
@Html.Partial("_EditarProv_Serv")

<script>

    $('#txtBuscar_').keyup(function () {
        if (this.value.length > 0) {
            $.uiTableFilter($('#tbListarProvServ_Usuario'), this.value);
        }
    });
    var URL_GET_PROVVEDOR_SERV = "@Url.Action("ListarProvee_Serv", "Proveedor_Servicio")";
    var URL_GET_ID_USUARIO = "@Url.Action("Buscar_x_idusuario", "Proveedor_Servicio")";
    var URL_GET_AGREGAR_USUARIO_PROVEEDOR = "@Url.Action("AgregarUsuario_Proveedor", "Proveedor_Servicio")";
    var URL_GET_LISTAR_USUARIO_PROVEEDOR = "@Url.Action("ListarProvServ_Usuario", "Proveedor_Servicio")";
    var URL_GET_ELIMINAR_USUARIO_PROVEEDOR = "@Url.Action("Desactivar_ProvUsuarios", "Proveedor_Servicio")";
    var URL_GET_LIST_CORREDOR = "@Url.Action("ListCorredores", "Proveedor_Servicio")";
    var URL_GET_AGREGARUSUARIO_CORREDOR = "@Url.Action("AgregarUsuarios_Corredor", "Proveedor_Servicio")";
    var URL_GET_ELIMINAR_USUARIO_CUENTA = "@Url.Action("Desactivar_Cuenta_Usuario", "Proveedor_Servicio")";
    var URL_GET_ACTUALIZAR_CONTRASEÑA = "@Url.Action("Actualizar_ContraseñaAnti", "Proveedor_Servicio")";
    var URL_GET_LIST_CORREDOR_X_USUPROV = "@Url.Action("ListCorredor_X_Usuprov", "Proveedor_Servicio")";
</script>

LOGINPUA/LOGINPUA/Views/Proveedor_Servicio/_EditarProv_Serv.cshtml
@{ List<ENTIDADES.CC_USUARIO_PERSONA> lisUsuario = new List
                <ENTIDADES.CC_USUARIO_PERSONA>(); lisUsuario = ViewBag.listaUsuario; }


<style>
    .focus:focus {
        color: red;
    }
</style>

 
<div class="modal fade" id="ActualizarModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h6 class="modal-title" id="tituloDialog">Editar Usuario Asignado a un Proovedor</h6>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <div class="form-group ">

                <div class="container">
                    <div class="row">

                        <div class="col-sm-3">
                            <h3 class="col-sm-2 col-form-label">Usuario</h3>
                        </div>

                        <div class="col-sm-6">
                            <select   id="idusuario_prove" class="selectpicker" data-live-search="true">
                                @foreach (var item in lisUsuario)
                                {
                                    <option value="@item.ID_USUARIO">@item.USUARIO</option>
                                }
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <button class="focus"><i class="fas fa-key btn-password" style="cursor:pointer"></i></button>    
                         </div>


                    </div>
                    <br />
                    <div class="row">
                        <div class="col-sm-3">

                            <h3 class="col-sm-2 col-form-label">Corredor</h3>
                        </div>

                        <div class="col-sm-8" id="idcorredores_div">

                        </div>
                    </div>
                </div>
            </div> 
            <div class="modal-footer">
                <button id="consultar1" onclick="AgregarUsuarios_Corredor($(this))" class="btn btn-info" type="button">
                    Guardar
                </button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<script>
     

</script>

LOGINPUA/LOGINPUA/Views/Proveedor_Servicio/_RegistroProv_Serv.cshtml
<div class="modal fade" id="exampleModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h6 class="modal-title" id="tituloDialog">Registrar Usuario Asignado a un Proovedor</h6>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <div class="form-group container">

                <fieldset class="border p-1">
                    <legend class="scheduler-border" style="font-size:18px">Asignacion de Proveedor Usuario</legend>
                    <div class="control-group">
                        <div class="form-group row">
                            <h3 class="col-sm-2 col-form-label">Proveedor</h3>
                            <div class="col-sm-3">
                                <select id="txtPROVEEDORSERV" style="width:137%" class="form-control" data-live-search="true"></select>
                            </div><div class="col-sm-1"></div>

                            <h3 class="col-sm-2 col-form-label">Usuario</h3>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="idusuario_prov" value="" />
                            </div>
                        </div>
                    </div>



                    <div class="form-group row">
                        <h3 class="col-sm-2 col-form-label">Contraseña</h3>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" style="width:100%" id="clave" name="name" value="" />
                        </div><div class="col-sm-1"></div>

                    </div> 
                </fieldset>

                <br />
                 
                <div class="modal-footer">
                    <button id="consultar" onclick="AgregarUsuarios_Proveedor()" class="btn btn-info" type="button">
                        Guardar
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>