LOGINPUA/LOGINPUA/Controllers/PerfilController.cs
using ENTIDADES;
using LN.EntidadesLN;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LOGINPUA.Controllers
{
    public class PerfilController : Controller
    {
        private readonly PerfilLN _PerfilLN;
        Util.Util utilidades = new Util.Util();


        public PerfilController(PerfilLN PerfilLN)
        {

            _PerfilLN = PerfilLN;
        }
        // GET: Perfil
        public ActionResult Perfil_Inicio()
        {
            var listaVistas = Session["menu_modulo"] as DataTable;
            var listacciones = Session["menu_acciones"] as List<CC_MENUPERFIL_ACCION>;
            //Session["menu_modulo"] = dt4;
            var nombreActionCurrent = this.ControllerContext.RouteData.Values["action"].ToString();
            bool auxValida = utilidades.validaVistaxPerfil(nombreActionCurrent, listaVistas);

            ViewBag.currentAction = this.ControllerContext.RouteData.Values["action"].ToString();
            ViewBag.currentRoute = this.ControllerContext.RouteData.Values["controller"].ToString();

 
            var Lista_acciones = utilidades.validadAccionMenu(listacciones, nombreActionCurrent, this.ControllerContext.RouteData.Values["controller"].ToString());

            if (auxValida)
            {
                ViewBag.Accionesview = Lista_acciones;
                return View();
            }
            else
            {
                return RedirectToAction("Sistemas_", "Home");
            }
         }

        public string listarPerfil(int idmodalidad)
        {
            var listar = _PerfilLN.ListarPerfil(idmodalidad);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }
        public string listarModalidad()
        {
            var listar = _PerfilLN.ListarModalidad();
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }

        public string ModificarPerfil(int idmodalidad, int id_modalidad_perfil, string nombre_perfil)
        {
            string session_usuario = Session["user_login"].ToString();
            var listar = _PerfilLN.ModificarPerfil(idmodalidad, id_modalidad_perfil, nombre_perfil, session_usuario);
            var result = JsonConvert.SerializeObject(listar); //para la lista principal
            return result;
        }
        public string AnularPerfil(int idperfil,string nombre_perfil)
        {
            var rpta = new RPTA_GENERAL();
            string session_usuario = Session["user_login"].ToString();

            var datos = _PerfilLN.Validar_Perfil(idperfil);

            if (datos.Count ==0)
            {
                rpta = _PerfilLN.AnularPerfil(idperfil, session_usuario);
            }
            else
            {
                rpta.COD_ESTADO = 0;
                rpta.DES_ESTADO = "Existen usuario con el perfil";
            }


            var result = JsonConvert.SerializeObject(rpta); //paraa anular
            return result;
        }
        public string AgregarPerfil(string nombre, int idmodalidad)
        {
            string session_usuario = "ADMINISTRADOR";

            //Se registra el Perfil
            var rpt = _PerfilLN.AgregarPerfil(nombre, session_usuario);
            var id_perfil = rpt.AUX;

            if (id_perfil != 0)
            {
                var rpt_final = _PerfilLN.AgregarPerfil_modalidad(id_perfil, idmodalidad, session_usuario);

            }

            var result = JsonConvert.SerializeObject(rpt); //para agregar
            return result;
        }

    }
}

LOGINPUA/LOGINPUA/Views/Perfil/Perfil_Inicio.cshtml
@{
    ViewBag.Title = "MantenimientoPerson";
    Layout = "~/Views/Shared/_LayoutInicial.cshtml";

    List<ENTIDADES.CC_MENUPERFIL_ACCION> Lista_acciones = ViewBag.Accionesview as List<ENTIDADES.CC_MENUPERFIL_ACCION>;
    int ideliminar = 0;
    int idmodificar = 0;
    
}

<style>
    .modal-dialog {
        max-width: max-content !important;
    }

    .modal-content input {
        width: auto !important;
    }

    .modal-content {
        width: 100%;
    }
</style>
<script src="~/Content/js/js_mantenimiento_perfil/registro_perfil.js@("?v="+ DateTime.Now.ToString("yyyyMMddhmmss"))"></script>



<br />
<div class="row">
    <div class="col-md-12 text-center">
        <h4>
            Registro Perfil&nbsp;&nbsp;&nbsp;

           
            @foreach (var item in Lista_acciones)
            {
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.REGISTRAR.ToString()) //cambiar a enumerado
                {
                    <button type="button" id="modal_registroperf" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal">
                        <span class="fa fa-plus"></span>
                    </button>
                }

                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.MODIFICAR.ToString())
                {
                    idmodificar = 1;
                    <input type="text" id="permisoActualiza" value="1" hidden />
                }
                if (item.NOMBRE == LOGINPUA.Enumerados.Acciones.EnumAcciones.ANULAR.ToString())
                {
                    ideliminar = 1;
                    <input type="text" id="permisoEliminar" value="1" hidden />
                }
            }




            <button type="button" class="btn btn-info btn-sm" id="btnBusquedaEnTabla">
                <span class="fa fa-search"></span>
            </button>
        </h4>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <div class="input-group mb-4" style="margin-bottom:0px !important">
            <div class="input-group-prepend">
                <span class="input-group-text" title="Corredor"><span class="fas fa-bus-alt"></span></span>
            </div>
            <select class="form-control form-control-sm" id="idmodalidad"></select>
        </div>
    </div>
</div>

<hr />

<div class="table-responsive">

    <form>
        <table class="responsive-table" id="tbPerfil" style="width:100%">
            <thead class="thead-azul-claro">
                <tr>
                    <th style="width: 40px;">N°</th>
                    <th class="text-center" style="width: 60px;">NOMBRE</th>
                    <th class="text-center" style="width: 60px;">MODALIDAD</th>
                    <th class="text-center" style="width: 90px;">USU_REG</th>
                    <th style="width: 125px;">FECHA_REG</th>


                    @if (ideliminar == 1)
                    {
                        <th class="text-center" style="width:50px;"></th>

                    }
                    @if (idmodificar == 1)
                    {
                        <th class="text-center" style="width:50px;"></th>

                    }


                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="13" class="text-center">Presionar el boton Consultar para obtener la información.</td>
                </tr>
            </tbody>
        </table>
    </form>
</div>

@Html.Partial("_RegistroPerfil")

<script>
    //$('#txtBuscar').keyup(function () {
    //    $.uiTableFilter($('#tbPerfil'), this.value);
    //});
    var URL_GET_PERFIL = "@Url.Action("listarPerfil", "Perfil")";
    var URL_GET_MODIFICAR_PERFIL = "@Url.Action("ModificarPerfil", "Perfil")";
    var URL_ANULAR_PERFIL = "@Url.Action("AnularPerfil", "Perfil")";
    var URL_GET_AGREGAR_PERFIL = "@Url.Action("AgregarPerfil", "Perfil")";
    var URL_GET_LISTAR_MODALIDAD = "@Url.Action("listarModalidad", "Perfil")";
</script>

LOGINPUA/LOGINPUA/Views/Perfil/_RegistroPerfil.cshtml
<div class="modal fade" id="exampleModal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">

            <div class="modal-header">
                <h6 class="modal-title" id="tituloDialog" style="text-align:center;">Registrar Perfil Para Corredor</h6>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <div class="form-group container">

                <div class="row">

                    <h3 class="col-sm-3 col-form-label">Nombre</h3>
                    <div class="col-sm-4">
                        <input type="text" class="form-control vacios" id="nombre" name="name" value="" autofocus />
                    </div>
                </div>

 
                    <br />

                    <div class="modal-footer">  
                        <button id="consultar" onclick="AgregarPerfil()" class="btn btn-info" type="button">
                            Guardar
                        </button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
 <script>
  

 
</script>